eureka:
  client:
    service-url:
      defaultZone: http://jachindo.top:8761/eureka/
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: Jachin_eureka
server:
  port: 8761