spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache
    username: root
    password: 5774857
    #    driver-class-name: com.mysql.jdbc.Driver  //可不写
  redis:
    host: 47.106.201.54


mybatis:
  configuration:
    map-underscore-to-camel-case: true
debug: true
