eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: Jachin_eureka
server:
  port: 8761