spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 5774857
    url: jdbc:mysql://39.106.177.45/sell?characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  http:
    encoding:
      charset: UTF-8
server:
  servlet:
    context-path: /sell